// tests/core_grid_test.cpp — headless render checks for the per-core views.
//
// These are the regressions that issues #2 and #3 were about, pinned as
// assertions against the REAL widgets rendered onto a real canvas:
//
//   #2  every per-core row must put its numeric columns at the same x. The
//       old grid dropped the temp cell to width(0) on cores with no probe and
//       let flex hand the rounding residue to the leading column, so rows
//       ragged by up to 5 cells. We render a machine with SPARSE per-core
//       temps — the exact shape of the reporter's screenshot — and assert the
//       '%' glyphs form a straight column.
//
//   #3  a heterogeneous machine must label every core with its cluster, and a
//       homogeneous one must not gain a phantom column.
//
// Run: cmake --build build --target rb_tests && ./build/rb_tests

#include <maya/maya.hpp>

#include "../src/core/metrics.hpp"
#include "../src/core/cluster_skew.hpp"
#include "../src/core/core_temps.hpp"
#include "../src/core/config.hpp"
#include "core/version.hpp"   // generated by CMake into the build dir
#include "../src/core/platform/linux/armid.hpp"
#include "../src/core/platform/linux/topology.hpp"
#include "../src/core/platform/common/sys_util.hpp"
#include "../src/ui/widgets/cpu_panel.hpp"
#include "../src/ui/widgets/detail/cpu.hpp"
#include "../src/ui/widgets/detail/mem.hpp"
#include "../src/ui/widgets/detail/net.hpp"
#include "../src/ui/widgets/detail/disk.hpp"
#include "../src/ui/proc_order.hpp"

#include <cctype>
#include <cmath>
#include <cstdio>
#include <map>
#include <string>
#include <vector>

using namespace rockbottom;

namespace {

int failures = 0;

void check(bool ok, const std::string& what) {
    std::printf("  %s %s\n", ok ? "\x1b[32mPASS\x1b[0m" : "\x1b[31mFAIL\x1b[0m", what.c_str());
    if (!ok) ++failures;
}

// Render an element at a fixed size and return it as plain text rows.
std::vector<std::string> render_rows(const maya::Element& e, int w, int h) {
    maya::StylePool pool;
    maya::Canvas canvas(w, h, &pool);
    maya::Theme theme;
    maya::render_tree(e, canvas, pool, theme);
    std::vector<std::string> out;
    for (int y = 0; y < canvas.height(); ++y) {
        std::string row;
        for (int x = 0; x < canvas.width(); ++x) {
            const char32_t c = canvas.get(x, y).character;
            // Fold every non-ASCII glyph (meters, sparks, box art) to a filler
            // so column arithmetic stays in cells, not bytes.
            row += (c < 128 && c != 0) ? static_cast<char>(c) : '.';
        }
        while (!row.empty() && row.back() == ' ') row.pop_back();
        out.push_back(row);
    }
    return out;
}

// Column offsets of every '%' in a row.
std::vector<int> pct_columns(const std::string& row) {
    std::vector<int> cols;
    for (std::size_t i = 0; i < row.size(); ++i)
        if (row[i] == '%') cols.push_back(static_cast<int>(i));
    return cols;
}

// How many '%' columns of a row belong to the thing under test.
//
// The dashboard CPU panel still lays cores out as an N-column GRID, so every
// '%' on the line is a core's and all of them must align. The DETAIL pane puts
// the per-core TABLE in its own column with unrelated content (the RIGHT NOW /
// DISTRIBUTION strips, whose values also carry '%') beside it on the same
// physical line — there only the table's own USE column, the FIRST one, is
// ours to compare. Comparing the neighbours' too would be asserting that two
// independent columns happen to share a rail, which is not a contract and was
// never true.
enum class Scan { AllColumns, LeadingColumn };

// Is this row a PER-CORE row?
//
// Both views put the core id first, so after stripping the panel border and
// indentation a core row starts with a digit ("7", "12·E") and carries a load
// percentage. Everything else in the pane — the ALL header, RIGHT NOW,
// DISTRIBUTION, the cluster headings — starts with a letter, so this cleanly
// isolates the grid we care about without hardcoding coordinates.
bool is_core_row(const std::string& row) {
    std::size_t i = 0;
    while (i < row.size() && !std::isalnum(static_cast<unsigned char>(row[i]))) ++i;
    if (i >= row.size() || !std::isdigit(static_cast<unsigned char>(row[i]))) return false;
    return row.find('%') != std::string::npos;
}

// A synthetic machine: `n` cores, optionally hybrid, with temps on only the
// cores whose index satisfies `temp_every` — the sparse pattern that exposed
// the alignment bug (the screenshot had temps on ~1 core in 4).
CpuInfo make_cpu(int n, bool hybrid, int temp_every) {
    CpuInfo c;
    c.model = "Test CPU";
    c.logical = n;
    c.total = Ratio{0.42};
    c.cores.resize(static_cast<std::size_t>(n));
    for (int i = 0; i < n; ++i) {
        CpuCore& k = c.cores[static_cast<std::size_t>(i)];
        k.usage = Ratio{static_cast<double>((i * 37) % 100) / 100.0};
        k.freq = Hertz{2'400'000'000ULL + static_cast<std::uint64_t>(i) * 100'000'000ULL};
        k.hist_len = 20;
        for (int j = 0; j < 20; ++j)
            k.history[static_cast<std::size_t>(j)] = static_cast<float>(((i + j) % 10) / 10.0);
        if (temp_every > 0 && i % temp_every == 0) k.temp_c = 60.0f + static_cast<float>(i % 8);
        if (hybrid) {
            // Half performance, half efficiency — Linux ordering (P first).
            k.kind = i < n / 2 ? CoreKind::Perf : CoreKind::Eff;
        }
    }
    if (hybrid) {
        c.perf_cores = n / 2;
        c.eff_cores = n - n / 2;
        c.perf_label = "Performance";
        c.eff_label = "Efficiency";
    }
    return c;
}

Snapshot make_snapshot(CpuInfo cpu) {
    Snapshot s;
    s.cpu = std::move(cpu);
    s.hostname = "testbox";
    s.kernel = "Test 1.0";
    return s;
}

// ── #2: the numeric columns must line up ─────────────────────────────
// Collect the rows that carry per-core figures and assert every one of them
// places its '%' at the same set of columns. A ragged grid produces different
// offsets per row — which is exactly what the reporter saw.
void test_alignment(const std::string& name, const std::vector<std::string>& rows,
                    Scan scan = Scan::AllColumns) {
    std::vector<std::vector<int>> shapes;
    for (const std::string& r : rows) {
        if (!is_core_row(r)) continue;
        std::vector<int> cols = pct_columns(r);
        if (cols.empty()) continue;
        if (scan == Scan::LeadingColumn) cols.resize(1);
        shapes.push_back(std::move(cols));
    }
    check(shapes.size() >= 2, name + ": found per-core rows to compare (" +
                                  std::to_string(shapes.size()) + ")");
    if (shapes.size() < 2) return;

    // Rows in a grid can hold a different NUMBER of cells (the last row may be
    // short), so compare each row's leading columns against the widest row's.
    std::size_t widest = 0;
    for (std::size_t i = 1; i < shapes.size(); ++i)
        if (shapes[i].size() > shapes[widest].size()) widest = i;

    bool aligned = true;
    std::string detail;
    for (const std::vector<int>& s : shapes) {
        for (std::size_t k = 0; k < s.size() && k < shapes[widest].size(); ++k) {
            if (s[k] != shapes[widest][k]) {
                aligned = false;
                detail = " (col " + std::to_string(k) + ": " + std::to_string(s[k]) +
                         " vs " + std::to_string(shapes[widest][k]) + ")";
                break;
            }
        }
        if (!aligned) break;
    }
    check(aligned, name + ": every core row's % lands in the same column" + detail);
}

void dump(const std::string& title, const std::vector<std::string>& rows) {
    std::printf("\n\x1b[2m--- %s ---\x1b[0m\n", title.c_str());
    for (const std::string& r : rows)
        if (!r.empty()) std::printf("\x1b[2m|\x1b[0m%s\n", r.c_str());
}

// Render the CPU detail pane body for a snapshot at a given size.
std::vector<std::string> render_detail(const Snapshot& s, int w, int h) {
    ui::detail::Ctx cx = ui::detail::Ctx::make(w, 50, 0);
    std::vector<maya::Element> col = ui::detail::cpu_body(s, cx);
    return render_rows((maya::dsl::v(std::move(col))).build(), w, h);
}

std::vector<std::string> render_body(std::vector<maya::Element> body, int w = 130, int h = 120) {
    return render_rows((maya::dsl::v(std::move(body))).build(), w, h);
}

bool contains_text(const std::vector<std::string>& rows, const std::string& needle) {
    for (const auto& row : rows)
        if (row.find(needle) != std::string::npos) return true;
    return false;
}

// ── topology fixtures ────────────────────────────────────────
// An in-memory sysfs: path -> contents. Lets the classifier be driven against
// the exact file layout of machines we don't have on hand.
using FakeFs = std::map<std::string, std::string>;

topo::ReadFile fs_reader(const FakeFs& fs) {
    return [&fs](const std::string& p) -> std::string {
        auto it = fs.find(p);
        return it == fs.end() ? std::string() : it->second;
    };
}

// Standard topology/ files: `n` logical cpus over `n/smt` physical cores.
void add_cpus(FakeFs& fs, int n, int smt = 1) {
    for (int i = 0; i < n; ++i) {
        const std::string b = "/sys/devices/system/cpu/cpu" + std::to_string(i) + "/topology/";
        fs[b + "core_id"] = std::to_string(i / smt);
        fs[b + "physical_package_id"] = "0";
    }
}

void add_scalar(FakeFs& fs, const std::string& suffix, const std::vector<long>& vals) {
    for (std::size_t i = 0; i < vals.size(); ++i)
        fs["/sys/devices/system/cpu/cpu" + std::to_string(i) + suffix] =
            std::to_string(vals[i]) + "\n";
}

std::string kinds_str(const topo::Topology& t) {
    if (t.kind.empty()) return "(homogeneous)";
    std::string s;
    for (CoreKind k : t.kind)
        s += k == CoreKind::Perf ? 'P' : k == CoreKind::Eff ? 'E' : '?';
    return s;
}

void expect_kinds(const std::string& name, const topo::Topology& t, const std::string& want) {
    const std::string got = kinds_str(t);
    check(got == want, name + ": " + got + (got == want ? "" : " (wanted " + want + ")"));
}

void test_topology() {
    std::printf("\nissue #3 — Linux topology classifier:\n");

    // Intel Core i7-12700H — 6 P cores with SMT (cpu0-11) + 8 E cores
    // (cpu12-19). The kernel names both clusters, so this must be exact.
    {
        FakeFs fs;
        add_cpus(fs, 20);
        fs["/sys/devices/cpu_core/cpus"] = "0-11\n";
        fs["/sys/devices/cpu_atom/cpus"] = "12-19\n";
        const topo::Topology t = topo::classify(20, fs_reader(fs));
        expect_kinds("alder lake i7-12700H", t, "PPPPPPPPPPPPEEEEEEEE");
        check(t.perf_label == "Performance", "alder lake: performance cluster named");
    }

    // A sparse/comma cpulist — the format is a list, not a single range.
    {
        FakeFs fs;
        add_cpus(fs, 8);
        fs["/sys/devices/cpu_core/cpus"] = "0-3,6\n";
        fs["/sys/devices/cpu_atom/cpus"] = "4,5,7\n";
        const topo::Topology t = topo::classify(8, fs_reader(fs));
        expect_kinds("sparse cpulist", t, "PPPPEEPE");
    }

    // ARM big.LITTLE (Snapdragon-style): 4 little + 4 big by DT capacity.
    {
        FakeFs fs;
        add_cpus(fs, 8);
        add_scalar(fs, "/cpu_capacity", {256, 256, 256, 256, 1024, 1024, 1024, 1024});
        const topo::Topology t = topo::classify(8, fs_reader(fs));
        expect_kinds("big.LITTLE capacity", t, "EEEEPPPP");
    }

    // Max-frequency inference, when neither of the better sources exists.
    {
        FakeFs fs;
        add_cpus(fs, 8);
        add_scalar(fs, "/cpufreq/cpuinfo_max_freq",
                   {2000000, 2000000, 2000000, 2000000, 3600000, 3600000, 3600000, 3600000});
        const topo::Topology t = topo::classify(8, fs_reader(fs));
        expect_kinds("max-freq inference", t, "EEEEPPPP");
        check(t.eff_label == "Slow", "max-freq: cluster labels are hedged (" + t.eff_label + ")");
    }

    // Homogeneous EPYC with binning scatter: clocks differ by ~1%, which is
    // NOT a cluster. Calling this hybrid would put a bogus P/E column on every
    // ordinary server — the regression this threshold exists to prevent.
    {
        FakeFs fs;
        add_cpus(fs, 16, 2);
        add_scalar(fs, "/cpufreq/cpuinfo_max_freq",
                   {3700000, 3700000, 3693000, 3700000, 3700000, 3688000, 3700000, 3700000,
                    3700000, 3695000, 3700000, 3700000, 3700000, 3700000, 3700000, 3690000});
        const topo::Topology t = topo::classify(16, fs_reader(fs));
        expect_kinds("homogeneous EPYC (binning scatter)", t, "(homogeneous)");
    }

    // Boost-clock quirk: one core certified 200MHz higher (Intel Turbo Boost
    // Max / AMD preferred core). Still one cluster.
    {
        FakeFs fs;
        add_cpus(fs, 8);
        add_scalar(fs, "/cpufreq/cpuinfo_max_freq",
                   {5000000, 4800000, 4800000, 4800000, 4800000, 4800000, 4800000, 4800000});
        const topo::Topology t = topo::classify(8, fs_reader(fs));
        expect_kinds("favoured-core boost quirk", t, "(homogeneous)");
    }

    // SMT sibling map: "Core 3" from Intel coretemp must reach BOTH threads.
    {
        FakeFs fs;
        add_cpus(fs, 16, 2);
        const topo::Topology t = topo::classify(16, fs_reader(fs));
        auto it = t.siblings.find(3);
        const bool paired = it != t.siblings.end() && it->second.size() == 2 &&
                            it->second[0] == 6 && it->second[1] == 7;
        check(paired, "physical core 3 maps to logical cpus 6 and 7");
    }

    // Multi-socket: both sockets have a "core 0", which must NOT collide.
    {
        FakeFs fs;
        for (int i = 0; i < 8; ++i) {
            const std::string b = "/sys/devices/system/cpu/cpu" + std::to_string(i) + "/topology/";
            fs[b + "core_id"] = std::to_string(i % 4);
            fs[b + "physical_package_id"] = std::to_string(i / 4);
        }
        const topo::Topology t = topo::classify(8, fs_reader(fs));
        check(t.siblings.size() == 8, "dual-socket: 8 distinct physical cores (got " +
                                          std::to_string(t.siblings.size()) + ")");
    }

    // Container with a masked /sys: no crash, no phantom cluster.
    {
        FakeFs fs;
        const topo::Topology t = topo::classify(4, fs_reader(fs));
        expect_kinds("masked /sys (container)", t, "(homogeneous)");
        check(t.phys.empty(), "masked /sys: no physical-core map");
    }

    // Partially readable capacity: refusing to guess beats mislabelling the
    // cores whose files didn't answer.
    {
        FakeFs fs;
        add_cpus(fs, 8);
        add_scalar(fs, "/cpu_capacity", {1024, 1024, 256, 256});   // only 4 of 8
        const topo::Topology t = topo::classify(8, fs_reader(fs));
        expect_kinds("partial capacity read", t, "(homogeneous)");
    }

    // Kernels that do NOT number core_id from 0. The ubuntu-24.04-arm CI
    // runner does exactly this — it numbers by MPIDR affinity, so the raw ids
    // are values like 36865 and the UI displayed them verbatim. The public
    // `phys` id must be dense and small, while the sensor-matching map keeps
    // the kernel's own numbering.
    {
        FakeFs fs;
        for (int i = 0; i < 4; ++i) {
            const std::string b = "/sys/devices/system/cpu/cpu" + std::to_string(i) + "/topology/";
            fs[b + "core_id"] = std::to_string(36865 + i);
            fs[b + "physical_package_id"] = "0";
        }
        const topo::Topology t = topo::classify(4, fs_reader(fs));
        const bool dense = t.phys.size() == 4 && t.phys[0] == 0 && t.phys[1] == 1 &&
                           t.phys[2] == 2 && t.phys[3] == 3;
        check(dense, "MPIDR core_ids are renumbered densely 0..3");
        check(t.by_core_id.count(36867) == 1,
              "kernel core_id 36867 still resolvable for sensor matching");
    }

    // Dense ids must not merge SMT siblings or collapse sockets.
    {
        FakeFs fs;
        add_cpus(fs, 16, 2);
        const topo::Topology t = topo::classify(16, fs_reader(fs));
        check(t.siblings.size() == 8, "SMT: 16 threads over 8 dense physical ids (got " +
                                          std::to_string(t.siblings.size()) + ")");
        int max_id = -1;
        for (int p : t.phys) max_id = std::max(max_id, p);
        check(max_id == 7, "SMT: dense ids stop at 7 (got " + std::to_string(max_id) + ")");
    }

    // Dual socket, dense: still 8 distinct cores, ids 0..7, no collision
    // between socket 0's "core 0" and socket 1's.
    {
        FakeFs fs;
        for (int i = 0; i < 8; ++i) {
            const std::string b = "/sys/devices/system/cpu/cpu" + std::to_string(i) + "/topology/";
            fs[b + "core_id"] = std::to_string(i % 4);
            fs[b + "physical_package_id"] = std::to_string(i / 4);
        }
        const topo::Topology t = topo::classify(8, fs_reader(fs));
        int max_id = -1;
        for (int p : t.phys) max_id = std::max(max_id, p);
        check(max_id == 7, "dual-socket: dense ids 0..7 (got max " + std::to_string(max_id) + ")");
        // Sensor matching is per-socket-ambiguous by nature; both sockets'
        // "core 0" must at least be reachable together rather than lost.
        check(t.by_core_id.at(0).size() == 2, "dual-socket: core_id 0 covers both sockets");
    }
}

// The ARM naming table — arm64 /proc/cpuinfo has no "model name" line, so
// without this every aarch64 machine reported the literal string "CPU".
// CI's ubuntu-24.04-arm runner is what exposed it.
void test_arm_names() {
    std::printf("\narm64 CPU naming (no \"model name\" in /proc/cpuinfo):\n");

    const struct { const char* impl; const char* part; const char* want; } cases[] = {
        {"0x41", "0xd0c", "ARM Neoverse-N1"},    // Graviton2 / Ampere Altra
        {"0x41", "0xd49", "ARM Neoverse-N2"},
        {"0x41", "0xd08", "ARM Cortex-A72"},     // Raspberry Pi 4
        {"0x41", "0xd03", "ARM Cortex-A53"},
        {"0xc0", "0xac3", "Ampere-1"},          // not "Ampere Ampere-1"
        {"0x61", "0x022", "Apple M1"},           // must not stutter "Apple Apple M1"
        {"65",   "3340",  "ARM Neoverse-N1"},    // decimal-formatted kernels
    };
    for (const auto& c : cases) {
        const std::string got = arm::model_name(c.impl, c.part);
        check(got == c.want, std::string(c.impl) + "/" + c.part + " -> \"" + got +
                                 "\"" + (got == c.want ? std::string() : " (wanted \"" + std::string(c.want) + "\")"));
    }

    // A known vendor with an unknown part still beats "CPU" in a bug report.
    {
        const std::string got = arm::model_name("0x41", "0xfff");
        check(got.rfind("ARM", 0) == 0 && got.find("fff") != std::string::npos,
              "unknown ARM part degrades to vendor + raw id (" + got + ")");
    }
    // Total garbage yields "", so the caller falls through to the board name.
    check(arm::model_name("", "").empty(), "empty ids yield no name");
    check(arm::model_name("0x99", "0x1").empty(), "unknown implementer yields no name");
}

// The "work is on the slow cores" advisory (issue #3's second ask). Pinned at
// the boundaries because a threshold that quietly stops firing still compiles
// and still looks reasonable — it just never speaks again.
void test_cluster_skew() {
    std::printf("\nissue #3 — work-on-slow-cores advisory:\n");

    // Build 4 E + 4 P cores at the given loads (percent).
    auto mk = [](double eff_pct, double perf_pct) {
        std::vector<CpuCore> v(8);
        for (int i = 0; i < 8; ++i) {
            const bool e = i < 4;
            v[static_cast<std::size_t>(i)].kind = e ? CoreKind::Eff : CoreKind::Perf;
            v[static_cast<std::size_t>(i)].usage = Ratio{(e ? eff_pct : perf_pct) / 100.0};
        }
        return v;
    };

    {
        const ClusterLoad c = cluster_load(mk(100, 5));
        check(c.eff_n == 4 && c.perf_n == 4, "counts both clusters");
        check(c.eff_avg > 99 && c.perf_avg < 6, "averages per cluster, not overall");
        check(c.misplaced(), "E pegged + P idle -> advise");
    }
    // The whole machine is busy: there is nowhere faster to move the work, so
    // the advice would be noise.
    check(!cluster_load(mk(100, 95)).misplaced(), "both clusters busy -> stay quiet");
    // Light background work on the E cluster is what it is FOR.
    check(!cluster_load(mk(40, 5)).misplaced(), "idle-ish E cluster -> stay quiet");
    // Inverted: heavy on P, quiet on E. Correct scheduling; nothing to say.
    check(!cluster_load(mk(5, 100)).misplaced(), "work already on P -> stay quiet");
    // Boundaries: strictly greater / strictly less.
    check(!cluster_load(mk(70, 10)).misplaced(), "E exactly at the 70% floor -> quiet");
    check(cluster_load(mk(71, 10)).misplaced(), "E just over the floor -> advise");
    check(!cluster_load(mk(90, 30)).misplaced(), "P exactly at the 30% ceiling -> quiet");
    check(cluster_load(mk(90, 29)).misplaced(), "P just under the ceiling -> advise");
    // A homogeneous machine has no clusters to be wrong about.
    {
        std::vector<CpuCore> flat(8);
        for (auto& c : flat) c.usage = Ratio{1.0};
        check(!cluster_load(flat).misplaced(), "homogeneous machine never advises");
    }
}

// The version must come from ONE place (the project() line in CMakeLists.txt,
// via the generated core/version.hpp). A second copy in a string literal is
// how a project ends up announcing the wrong number from a correct binary —
// invisible until it lands in someone's bug report.
void test_version() {
    std::printf("\nversion is centralised:\n");

    const std::string v = kVersion;
    check(!v.empty(), "version is non-empty");

    // Shape: major.minor.patch, digits and dots only.
    int dots = 0;
    bool shape_ok = !v.empty();
    for (char ch : v) {
        if (ch == '.') ++dots;
        else if (!std::isdigit(static_cast<unsigned char>(ch))) shape_ok = false;
    }
    check(shape_ok && dots == 2, "version is major.minor.patch (" + v + ")");

    // The components must agree with the string — they all come from the same
    // configure_file expansion, so a mismatch means the template drifted.
    const std::string from_parts = std::to_string(kVersionMajor) + "." +
                                   std::to_string(kVersionMinor) + "." +
                                   std::to_string(kVersionPatch);
    check(from_parts == v, "numeric components match the string (" + from_parts + ")");

    // And the line `rb --version` prints must be derived from it, not typed.
    const std::string line = kVersionLine;
    check(line == "rockbottom " + v, "--version line derives from it (" + line + ")");

    // The real check: parse_args must emit exactly that line. This is what
    // actually regressed — config.hpp used to hardcode "rockbottom 1.0" while
    // CMake said 1.0.0.
    {
        Config c;
        std::string msg;
        bool ok = false;
        char arg0[] = "rb", arg1[] = "--version";
        char* argv[] = {arg0, arg1};
        const bool cont = Config::parse_args(2, argv, c, msg, ok);
        check(!cont && ok, "--version exits cleanly");
        check(msg == line + "\n", "rb --version prints \"" + line + "\"");
    }
}

// Per-core temperature resolution. The interesting case is the one Apple
// Silicon actually presents: the platform publishes a temperature PER CLUSTER,
// not per core, and before this the whole column rendered as dashes. Driven
// through the public Sampler so the real resolution path runs.
void test_core_temps() {
    std::printf("\nper-core temperature resolution:\n");

    // A cluster-labelled sensor must reach every core of that cluster, and
    // must NOT bleed across into the other one.
    {
        CpuInfo cpu = make_cpu(8, true, 0);   // hybrid, no per-core temps
        std::vector<Sensor> sensors{
            {"CPU performance", "cpu", 74.4f, 0, 0},
            {"CPU efficiency",  "cpu", 64.3f, 0, 0},
        };
        resolve_core_temps(cpu, sensors, {});

        bool perf_ok = true, eff_ok = true;
        for (const CpuCore& c : cpu.cores) {
            if (c.kind == CoreKind::Perf && std::abs(c.temp_c - 74.4f) > 0.01f) perf_ok = false;
            if (c.kind == CoreKind::Eff  && std::abs(c.temp_c - 64.3f) > 0.01f) eff_ok  = false;
        }
        check(perf_ok, "cluster sensor fans out to every P core");
        check(eff_ok,  "cluster sensor fans out to every E core");
        // Package = hottest CPU-zone reading, so "is anything cooking?" is
        // answerable; a mean would hide exactly that.
        check(std::abs(cpu.temp_c - 74.4f) < 0.01f,
              "package temp is the hottest CPU sensor (" + std::to_string(cpu.temp_c) + ")");
    }

    // A real PER-CORE sensor must win over the cluster fallback.
    {
        CpuInfo cpu = make_cpu(4, false, 0);
        for (CpuCore& c : cpu.cores) c.kind = CoreKind::Perf;
        std::vector<Sensor> sensors{
            {"Core 2",          "cpu", 91.0f, 0, 0},
            {"CPU performance", "cpu", 70.0f, 0, 0},
        };
        std::unordered_map<int, std::vector<int>> by_core_id{{2, {2}}};
        resolve_core_temps(cpu, sensors, by_core_id);
        check(std::abs(cpu.cores[2].temp_c - 91.0f) < 0.01f,
              "per-core sensor beats the cluster average");
        check(std::abs(cpu.cores[0].temp_c - 70.0f) < 0.01f,
              "cores without their own sensor still get the cluster figure");
    }

    // Nothing readable: everything stays at the sentinel so the UI omits the
    // column rather than printing a confident zero.
    {
        CpuInfo cpu = make_cpu(4, false, 0);
        resolve_core_temps(cpu, {}, {});
        bool all_zero = cpu.temp_c == 0;
        for (const CpuCore& c : cpu.cores) if (c.temp_c != 0) all_zero = false;
        check(all_zero, "no sensors -> no invented temperatures");
    }
}

}  // namespace

// ── the PER-CORE TABLE contract ────────────────────────────────────
// The table promises four things at EVERY terminal size and core count, and
// each is a bug someone would file if it broke:
//
//   1. ONE ROW PER CORE — exactly n core rows plus the ALL package row. A grid
//      that silently packed two cores onto a line, or dropped the tail of a
//      256-thread machine, would look plausible in a screenshot.
//   2. The USE column sits at ONE x for the header and every row, so the
//      numbers read as a column (this is issue #2, now table-shaped).
//   3. Nothing OVERFLOWS its slot — no row is longer than the pane, so no
//      number can be pushed off-screen or wrap into the row below.
//   4. Every core's LOAD is legible: its own "NN%" appears on its own row.
//
// Runs over a large matrix, so it accumulates FAILURE STRINGS rather than
// printing a PASS line per case — a hundred green lines would bury the red one.
std::vector<std::string> table_faults;

void test_core_table(int n, bool hybrid, int temp_every, int w) {
    const std::string name = "n=" + std::to_string(n) + " w=" + std::to_string(w)
                           + (hybrid ? " hybrid" : "") + " t/" + std::to_string(temp_every);
    const CpuInfo cpu = make_cpu(n, hybrid, temp_every);
    const auto rows = render_detail(make_snapshot(cpu), w, 40 + n * 3);
    auto fault = [&](const std::string& why) { table_faults.push_back(name + ": " + why); };

    // Locate the table by its header — the row carrying the USE label. Its '%'
    // rail is then the rail every core row must hit.
    int use_x = -1;
    int table_x = -1;
    for (const std::string& r : rows) {
        const std::size_t k = r.find("USE");
        const std::size_t load = r.find("LOAD");
        if (k != std::string::npos && load != std::string::npos) {
            use_x = static_cast<int>(k) + 2;   // 'USE' is right-aligned on '%'
            // The core table may be either the left or right detail rail.
            // Keep its own x-origin so summary rows on the other rail cannot
            // be mistaken for table entries.
            table_x = static_cast<int>(r.rfind("CORE", load));
            if (table_x < 0) table_x = static_cast<int>(r.rfind("CPU", load));
            break;
        }
    }
    if (use_x < 0 || table_x < 0) { fault("no table header"); return; }

    // A core row is one whose FIRST token is this table's id — count them.
    int core_rows = 0, all_rows = 0, misaligned = 0, overflow = 0;
    for (const std::string& r : rows) {
        if (static_cast<int>(r.size()) > w) ++overflow;
        // Read only the table's own left cell. In ultrawide mode another
        // column can contain bars and percentages before this table begins.
        const std::size_t begin = std::min<std::size_t>(table_x, r.size());
        const std::size_t end = std::min<std::size_t>(use_x, r.size());
        std::size_t i = begin;
        while (i < end && r[i] == ' ') ++i;
        if (i >= end) continue;
        const std::vector<int> pc = pct_columns(r);
        // A row belongs to this table only when it reaches THIS table's USE
        // rail—not merely because an adjacent summary rail contains a number.
        if (std::find(pc.begin(), pc.end(), use_x) == pc.end()) continue;
        const bool is_all = r.compare(i, 3, "ALL") == 0;
        const bool is_core = std::isdigit(static_cast<unsigned char>(r[i]));
        if (!is_all && !is_core) continue;
        if (is_all) ++all_rows; else ++core_rows;
    }
    if (core_rows != n)
        fault("expected " + std::to_string(n) + " core rows, got " + std::to_string(core_rows));
    if (all_rows != 1)
        fault("expected 1 ALL row, got " + std::to_string(all_rows));
    if (misaligned)
        fault(std::to_string(misaligned) + " row(s) off the USE rail at x=" + std::to_string(use_x));
    if (overflow)
        fault(std::to_string(overflow) + " row(s) wider than " + std::to_string(w));
}

// Terminal-escape-injection defense: process names / command lines are
// attacker-controlled, so sanitize_display() must neutralize every terminal
// control introducer while leaving legitimate UTF-8 untouched. A regression
// here silently reopens a real vulnerability, so it is asserted, not just
// eyeballed.
void test_sanitize() {
    using rockbottom::sys::sanitize_display;
    std::printf("\nsecurity — process-name escape injection is neutralized:\n");

    // A string is unsafe if, decoded as UTF-8, any codepoint is a control
    // (C0/DEL/C1) or any byte is not part of a well-formed sequence.
    auto unsafe = [](const std::string& s) {
        std::size_t i = 0, n = s.size();
        auto cont = [&](std::size_t k){ return k < n && (static_cast<unsigned char>(s[k]) & 0xC0) == 0x80; };
        while (i < n) {
            unsigned char c = static_cast<unsigned char>(s[i]);
            char32_t cp; std::size_t len;
            if (c < 0x80) { cp = c; len = 1; }
            else if ((c & 0xE0) == 0xC0 && cont(i+1)) { cp = ((c & 0x1F) << 6) | (static_cast<unsigned char>(s[i+1]) & 0x3F); len = 2; }
            else if ((c & 0xF0) == 0xE0 && cont(i+1) && cont(i+2)) { cp = (static_cast<char32_t>(c & 0x0F) << 12) | ((static_cast<unsigned char>(s[i+1]) & 0x3F) << 6) | (static_cast<unsigned char>(s[i+2]) & 0x3F); len = 3; }
            else if ((c & 0xF8) == 0xF0 && cont(i+1) && cont(i+2) && cont(i+3)) { cp = (static_cast<char32_t>(c & 0x07) << 18) | ((static_cast<char32_t>(static_cast<unsigned char>(s[i+1]) & 0x3F)) << 12) | ((static_cast<unsigned char>(s[i+2]) & 0x3F) << 6) | (static_cast<unsigned char>(s[i+3]) & 0x3F); len = 4; }
            else return true;   // malformed byte
            if (cp < 0x20 || cp == 0x7f || (cp >= 0x80 && cp <= 0x9f)) return true;
            i += len;
        }
        return false;
    };

    // Every injection payload must come out safe.
    const std::string payloads[] = {
        std::string("evil\x1b[2Jname"),        // C0 CSI (clear screen)
        std::string("t\x1b]0;pwned\x07"),      // OSC window-title / clipboard
        std::string("a\x9b" "31mRED"),          // 8-bit CSI (0x9b) — maya passes this through
        std::string("b\x9d" "x\x9c"),           // 8-bit OSC + ST
        std::string("c\x7f" "d"),               // DEL
        std::string("e\xC2\x9B" "f"),          // UTF-8-encoded C1 CSI
        std::string("\x80\x81lone"),            // lone continuation bytes
        std::string("trunc\xE4\xBD"),           // truncated 3-byte sequence
        std::string("over\xC0\x80"),            // overlong NUL
    };
    bool all_safe = true;
    for (const auto& p : payloads)
        if (unsafe(sanitize_display(p))) all_safe = false;
    check(all_safe, "all terminal-control payloads are neutralized");

    // Legitimate UTF-8 must survive byte-for-byte (no false positives that
    // would mangle real process names).
    const std::string legit = "caf\xC3\xA9 \xC2\xA0 \xE4\xBD\xA0\xE5\xA5\xBD \xF0\x9F\x9A\x80";
    check(sanitize_display(legit) == legit,
          "accents / nbsp / CJK / emoji pass through unchanged");
    check(sanitize_display("normal-proc") == "normal-proc" && sanitize_display("").empty(),
          "plain names and empty strings are unchanged");
}

void test_proc_order_strictness() {
    std::printf("\nprocess sorting is a strict weak ordering:\n");

    ProcInfo a{}, b{};
    a.pid = 20;
    b.pid = 10;
    a.name = b.name = "same";
    a.cpu = b.cpu = 42.0;
    a.rss = b.rss = Bytes{4096};
    a.io_read.per_sec = b.io_read.per_sec = 128.0;

    constexpr SortKey keys[] = {SortKey::Cpu, SortKey::Mem, SortKey::Io,
                                SortKey::Pid, SortKey::Name, SortKey::Port};
    bool irreflexive = true, antisymmetric = true;
    for (SortKey key : keys) {
        for (bool desc : {false, true}) {
            irreflexive &= !ui::proc_less(a, a, key, desc) &&
                           !ui::proc_less(b, b, key, desc);
            antisymmetric &= !(ui::proc_less(a, b, key, desc) &&
                               ui::proc_less(b, a, key, desc));
        }
    }
    check(irreflexive, "no process compares less than itself in either direction");
    check(antisymmetric, "equal primary keys use a one-way pid tiebreak");

    // Distinct values pin the direction contract too: magnitude columns are
    // naturally largest-first, while pid/name are naturally ascending.
    a.cpu = 90.0; b.cpu = 10.0;
    a.rss = Bytes{9000}; b.rss = Bytes{1000};
    a.io_read.per_sec = 900.0; b.io_read.per_sec = 100.0;
    a.name = "zeta"; b.name = "alpha";
    a.ports = {8080}; b.ports.clear();
    check(ui::proc_less(a, b, SortKey::Cpu, true) &&
          ui::proc_less(b, a, SortKey::Cpu, false),
          "cpu direction toggles largest-first / smallest-first");
    check(ui::proc_less(a, b, SortKey::Mem, true) &&
          ui::proc_less(b, a, SortKey::Mem, false),
          "memory direction toggles largest-first / smallest-first");
    check(ui::proc_less(a, b, SortKey::Io, true) &&
          ui::proc_less(b, a, SortKey::Io, false),
          "I/O direction toggles largest-first / smallest-first");
    check(ui::proc_less(b, a, SortKey::Pid, false) &&
          ui::proc_less(a, b, SortKey::Pid, true),
          "pid direction toggles ascending / descending");
    check(ui::proc_less(b, a, SortKey::Name, false) &&
          ui::proc_less(a, b, SortKey::Name, true),
          "name direction toggles A-first / Z-first");
    check(ui::proc_less(a, b, SortKey::Port, true) &&
          ui::proc_less(b, a, SortKey::Port, false),
          "port direction toggles bound-first / unbound-first");

    // Restore equal values for the deterministic tiebreak assertion.
    a.cpu = b.cpu = 42.0;
    std::vector<const ProcInfo*> rows{&a, &b};
    const auto ordered = ui::order_flat(rows, SortKey::Cpu, false);
    check(ordered.procs.size() == 2 && ordered.procs[0]->pid == 10 &&
          ordered.procs[1]->pid == 20,
          "equal-value rows have deterministic pid order");
}

int main() {
    std::printf("\n\x1b[1mper-core grid tests\x1b[0m\n\n");

    test_topology();
    test_arm_names();
    test_cluster_skew();
    test_version();
    test_core_temps();
    test_sanitize();
    test_proc_order_strictness();

    // ── device-health visibility: issues #4–#8 ──────────────────────
    // These probes must be visually verifiable on a healthy, ordinary host;
    // hiding a clean/unsupported state made the delivered features look absent.
    {
        std::printf("\ndevice-health telemetry is visible at rest:\n");
        Snapshot s = make_snapshot(make_cpu(4, false, 0));
        s.mem.total = Bytes{16ull * 1024 * 1024 * 1024};
        s.mem.available = Bytes{8ull * 1024 * 1024 * 1024};
        s.nets.push_back(NetIface{.name = "eth0", .up = true});
        const ui::detail::Ctx cx = ui::detail::Ctx::make(130, 70, 0);

        const auto mem = render_body(ui::detail::mem_body(s, cx));
        check(contains_text(mem, "HUGEPAGES & NUMA"),
              "MEMORY always labels hugepage and NUMA telemetry");
        check(contains_text(mem, "none configured") && contains_text(mem, "numa balancing"),
              "MEMORY reports an explicit no-pool / NUMA-off baseline");

        const auto net = render_body(ui::detail::net_body(s, cx));
        check(contains_text(net, "rx errors") && contains_text(net, "tx errors") &&
              contains_text(net, "dropped in"),
              "NETWORK always labels clean interface error/drop counters");

        const auto disk = render_body(ui::detail::disk_body(s, cx));
        check(contains_text(disk, "DEVICE HEALTH"),
              "DISK always labels latency and endurance telemetry");
        check(contains_text(disk, "no block-device latency telemetry") &&
              contains_text(disk, "NVMe SMART endurance unavailable"),
              "DISK explains unavailable latency and NVMe SMART data");

        // Populate every source's actionable state too: this verifies that
        // the detailed readings and warnings survive the collector → snapshot
        // → pane path, not merely the empty-state labels above.
        Snapshot active = s;
        active.mem.huge_total = 128;
        active.mem.huge_free = 96;
        active.mem.huge_rsvd = 8;
        active.mem.huge_size = Bytes{2ull * 1024 * 1024};
        active.mem.huge_idle = Bytes{176ull * 1024 * 1024};
        active.mem.numa_on = true;
        active.mem.numa_hint_faults_ps = 25'000;
        active.nets[0].rx_errs = 3;
        active.nets[0].tx_errs = 2;
        active.nets[0].drops = 7;
        active.nets[0].err_ps = 2;
        active.nets[0].drop_ps = 5;
        active.drives.push_back(DriveIO{.name = "nvme0n1", .read_lat_ms = 3.2,
                                        .write_lat_ms = 88.0, .busy = 0.82});
        active.ssd_health.push_back(SsdHealth{.name = "nvme0", .pct_used = 90,
                                               .spare_pct = 8, .spare_thresh = 10});
        const auto active_mem = render_body(ui::detail::mem_body(active, cx));
        const auto active_net = render_body(ui::detail::net_body(active, cx));
        const auto active_disk = render_body(ui::detail::disk_body(active, cx));
        check(contains_text(active_mem, "pool in use") && contains_text(active_mem, "hint faults"),
              "MEMORY renders hugepage use and NUMA fault evidence");
        check(contains_text(active_net, "drops/s") && contains_text(active_net, "link errors/s"),
              "NETWORK renders live error and drop-rate warnings");
        check(contains_text(active_disk, "88.0 ms") && contains_text(active_disk, "90% worn") &&
              contains_text(active_disk, "needs attention"),
              "DISK renders latency, endurance, and SMART-spare warnings");
    }

    // ── issue #2: sparse temps must not shift rows ─────────────────-
    // 130 cols keeps the pane in SINGLE-column mode (ultrawide splits at 146),
    // so the per-core grid owns whole rows and every one of them is compared.
    {
        std::printf("issue #2 — detail pane, 22 cores, temps on 1 in 4:\n");
        const auto rows = render_detail(make_snapshot(make_cpu(22, false, 4)), 130, 60);
        test_alignment("detail/sparse-temps", rows, Scan::LeadingColumn);
        dump("detail pane (22 cores, sparse temps)", rows);
    }

    // ── same shape, no temps at all ──────────────────────────────
    {
        std::printf("\nissue #2 — detail pane, 22 cores, no per-core temps:\n");
        const auto rows = render_detail(make_snapshot(make_cpu(22, false, 0)), 130, 60);
        test_alignment("detail/no-temps", rows, Scan::LeadingColumn);
    }

    // ── the reporter's exact shape: temps on a sparse, IRREGULAR subset ────
    // In the screenshot cores 0-8, 12, 16 and 20 had a °C figure and the rest
    // did not — the row-by-row asymmetry that made the old grid rag.
    {
        std::printf("\nissue #2 — irregular temp coverage (screenshot shape):\n");
        CpuInfo cpu = make_cpu(22, false, 0);
        for (int i : {0, 1, 2, 3, 4, 5, 6, 7, 8, 12, 16, 20})
            cpu.cores[static_cast<std::size_t>(i)].temp_c = 60.0f + static_cast<float>(i % 9);
        const auto rows = render_detail(make_snapshot(cpu), 130, 60);
        test_alignment("detail/irregular-temps", rows, Scan::LeadingColumn);
        dump("detail pane (irregular temps)", rows);
    }

    // ── narrow / awkward widths must stay aligned too ──────────────────
    // Column count and spark width both change across these; the alignment
    // contract must hold at every one, including widths that do not divide
    // evenly by the column count (where flex used to smear the residue).
    {
        std::printf("\nissue #2 — alignment holds across widths:\n");
        for (int w : {71, 83, 100, 107, 128, 141, 173, 199}) {
            const auto rows = render_detail(make_snapshot(make_cpu(22, false, 4)), w, 70);
            test_alignment("detail/w=" + std::to_string(w), rows, Scan::LeadingColumn);
        }
        for (int w : {64, 90, 113, 130, 161}) {
            const CpuInfo cpu = make_cpu(22, false, 4);
            const auto rows = render_rows(ui::CpuPanel(cpu, 3, 46, 4).build(), w, 24);
            test_alignment("panel/w=" + std::to_string(w), rows);
        }
    }

    // ── dashboard panel grid ───────────────────────────────────
    {
        std::printf("\nissue #2 — dashboard CPU panel, 22 cores, 3 columns:\n");
        const CpuInfo cpu = make_cpu(22, false, 4);
        const auto rows = render_rows(ui::CpuPanel(cpu, 3, 46, 4).build(), 130, 24);
        test_alignment("panel/3-col", rows);
        dump("dashboard panel (22 cores)", rows);
    }

    // ── issue #3: hybrid machines label every core ──────────────────
    {
        std::printf("\nissue #3 — hybrid machine, per-core P/E labels:\n");
        const auto rows = render_detail(make_snapshot(make_cpu(16, true, 0)), 130, 70);

        int p_tags = 0, e_tags = 0;
        for (const std::string& r : rows)
            for (std::size_t i = 1; i + 1 < r.size(); ++i) {
                // ids render as "NN.P" / "NN.E" (the · folds to '.').
                if (r[i] == '.' && (r[i + 1] == 'P' || r[i + 1] == 'E')
                    && std::isdigit(static_cast<unsigned char>(r[i - 1]))) {
                    if (r[i + 1] == 'P') ++p_tags; else ++e_tags;
                }
            }
        check(p_tags == 8, "8 cores tagged P (got " + std::to_string(p_tags) + ")");
        check(e_tags == 8, "8 cores tagged E (got " + std::to_string(e_tags) + ")");

        // The clusters must be grouped under their own headings, and the
        // pane must name both — that IS the feature issue #3 asked for.
        bool perf_heading = false, eff_heading = false;
        for (const std::string& r : rows) {
            if (r.find("Performance") != std::string::npos) perf_heading = true;
            if (r.find("Efficiency") != std::string::npos)  eff_heading = true;
        }
        check(perf_heading, "performance cluster is titled");
        check(eff_heading, "efficiency cluster is titled");
        test_alignment("detail/hybrid", rows, Scan::LeadingColumn);
        dump("detail pane (hybrid 8P+8E)", rows);
    }

    // ── the panel shows the class too, not just the drill-down ──────────
    {
        std::printf("\nissue #3 — dashboard panel tags cores:\n");
        const CpuInfo cpu = make_cpu(16, true, 0);
        const auto rows = render_rows(ui::CpuPanel(cpu, 2, 46, 4).build(), 120, 20);
        int tags = 0;
        for (const std::string& r : rows)
            for (std::size_t i = 1; i + 1 < r.size(); ++i)
                if (r[i] == '.' && (r[i + 1] == 'P' || r[i + 1] == 'E')
                    && std::isdigit(static_cast<unsigned char>(r[i - 1]))) ++tags;
        check(tags == 16, "all 16 cores tagged in the panel (got " + std::to_string(tags) + ")");
        test_alignment("panel/hybrid", rows);
        dump("dashboard panel (hybrid)", rows);
    }

    // ── homogeneous machines must NOT grow cluster chrome ───────────────
    {
        std::printf("\nissue #3 — homogeneous machine stays flat:\n");
        const auto rows = render_detail(make_snapshot(make_cpu(8, false, 0)), 130, 60);
        bool has_cluster = false;
        for (const std::string& r : rows)
            if (r.find("PERFORMANCE") != std::string::npos ||
                r.find("Performance") != std::string::npos ||
                r.find("EFFICIENCY") != std::string::npos) has_cluster = true;
        check(!has_cluster, "no cluster headings on a homogeneous machine");
    }

    // ── the per-core TABLE, across every shape a machine can have ──────────
    // One core per row, aligned to its header, never overflowing — asserted
    // over the whole matrix of core counts × widths × hybrid × temp coverage.
    // The extremes are the point: 1 core on a 24-col phone terminal and 256
    // threads on an ultrawide are the two ends where a layout breaks.
    {
        std::printf("\nper-core TABLE — one row per core at every size:\n");
        int cases = 0;
        auto run = [&](int n, bool hy, int te, int w) { ++cases; test_core_table(n, hy, te, w); };
        for (int n : {1, 2, 4, 8, 22, 64, 128, 256})
            for (int w : {24, 40, 71, 100, 130, 173, 240})
                run(n, false, 4, w);
        // Hybrid: the cluster headings and the ·P/·E id tag both widen the id
        // column, which is exactly where an off-by-one would show up.
        for (int n : {2, 8, 16, 24, 128})
            for (int w : {24, 40, 71, 100, 130, 173, 240})
                run(n, true, 0, w);
        // Temp coverage variants: none, sparse, every core. The °C column is
        // reserve-and-blank, so a core with no probe must not shift its row.
        for (int te : {0, 1, 3, 7})
            for (int w : {40, 71, 100, 130, 173})
                run(22, false, te, w);

        check(table_faults.empty(),
              std::to_string(cases) + " shapes: one row per core, on the header rail, "
              "nothing overflowing");
        for (std::size_t i = 0; i < table_faults.size() && i < 12; ++i)
            std::printf("       → %s\n", table_faults[i].c_str());
        if (table_faults.size() > 12)
            std::printf("       → … and %zu more\n", table_faults.size() - 12);
    }

    std::printf("\n%s\n\n", failures ? ("\x1b[31m" + std::to_string(failures) +
                                        " check(s) failed\x1b[0m").c_str()
                                     : "\x1b[32mall checks passed\x1b[0m");
    return failures ? 1 : 0;
}
